[input_parameters]
Lx = 10.0
Ly = 10.0
Lz = 1.0
mi_me = 25.0
Ti_Te = 1.0
qs = [-1.0, 1.0]
alpha_s = [0.25, 0.25, 0.25, 0.05, 0.05, 0.05]
u_s = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
Omega_cs = [0.5, 0.02]
nu = 1.0
D = 0.0
t_max = 0.2
vte = 0.177
vti = 0.0354
ode_tolerance = 1e-5

[solver_parameters]
Nx = 17
Ny = 17
Nz = 1
Nn = 4
Nm = 4
Np = 4
Ns = 2
timesteps = 501
dt = 0.1
solver = "Dopri8"