[input_parameters]
Lx = 1.0
Ly = 1.0
Lz = 1.0
mi_me = 1836.0
Ti_Te = 1.0
qs = [-1.0, 1.0]
alpha_e = [0.1, 0.1, 0.1]
alpha_s = [0.1, 0.1, 0.1, 0.0023, 0.0023, 0.0023]
u_s = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
Omega_cs = [1.0, 0.00054]
nu = 1.0
t_max = 50.0
nx = 1
ny = 0
nz = 0
dn1 = 0.5
ode_tolerance = 1e-8

[solver_parameters]
Nx=33
Ny=1
Nz=1
Nn=40
Nm=1
Np=1
Ns=2
timesteps=501
dt=0.01
solver="Dopri8"