[input_parameters]
Lx = 1.0
Ly = 1.0
Lz = 1.0
mi_me = 1836.0
Ti_Te = 1.0
qs = [-1.0, 1.0]
alpha_e = [0.1, 0.1, 0.1]
alpha_s = [0.1, 0.1, 0.1, 0.0023, 0.0023, 0.0023]
u_s = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
Omega_cs = [1.0, 0.00054]
nu = 1.0
t_max = 100.0
nx = 0
ny = 0
nz = 1
dn1 = 0.000001
ode_tolerance = 1e-10

[solver_parameters]
Nx=1
Ny=1
Nz=33
Nn=1
Nm=1
Np=40
Ns=2
timesteps=1000
solver="Dopri8"